import numpy as np
import matplotlib.pyplot as plt

# Fungsi keanggotaan segitiga
def triangular(x, a, b, c):
    return np.maximum(0, np.minimum((x - a) / (b - a), (c - x) / (c - b)))

# Fungsi keanggotaan trapesium
def trapezoidal(x, a, b, c, d):
    return np.maximum(0, np.minimum(np.minimum((x - a) / (b - a), 1), (d - x) / (d - c)))

# Setup plot
fig, axes = plt.subplots(4, 3, figsize=(18, 15))
fig.suptitle('12 KURVA FUNGSI KEANGGOTAAN FUZZY', fontsize=16, fontweight='bold')

# 1. SKALA RICHTER (3 kurva)
x_sr = np.linspace(0, 8, 1000)
low_sr = triangular(x_sr, 0, 4, 5)
medium_sr = trapezoidal(x_sr, 4, 5, 5.8, 6.2)  
high_sr = triangular(x_sr, 5.8, 6.2, 8)

axes[0,0].plot(x_sr, low_sr, 'b-', linewidth=2, label='LOW')
axes[0,0].axvline(4.0, color='blue', linestyle='--', alpha=0.7)
axes[0,0].plot(4.0, 1.0, 'bo', markersize=8)
axes[0,0].set_title('1. Skala Richter → LOW\nSR=4.0, μ=1.0')
axes[0,0].set_xlabel('Skala Richter')
axes[0,0].set_ylabel('μ')
axes[0,0].grid(True)
axes[0,0].legend()

axes[0,1].plot(x_sr, medium_sr, 'g-', linewidth=2, label='MEDIUM')
axes[0,1].axvline(4.1, color='green', linestyle='--', alpha=0.7)
axes[0,1].plot(4.1, 0.1, 'go', markersize=8)
axes[0,1].set_title('2. Skala Richter → MEDIUM\nSR=4.1, μ=0.1')
axes[0,1].set_xlabel('Skala Richter')
axes[0,1].set_ylabel('μ')
axes[0,1].grid(True)
axes[0,1].legend()

axes[0,2].plot(x_sr, high_sr, 'r-', linewidth=2, label='HIGH')
axes[0,2].axvline(5.8, color='red', linestyle='--', alpha=0.7)
axes[0,2].plot(5.8, 1.0, 'ro', markersize=8)
axes[0,2].set_title('3. Skala Richter → HIGH\nSR=5.8, μ=1.0')
axes[0,2].set_xlabel('Skala Richter')
axes[0,2].set_ylabel('μ')
axes[0,2].grid(True)
axes[0,2].legend()

# 2. PERSENTASE SINYAL (3 kurva)
x_ps = np.linspace(0, 100, 1000)
sedikit_ps = triangular(x_ps, 0, 35, 45)
cukup_ps = trapezoidal(x_ps, 35, 45, 55, 75)
banyak_ps = triangular(x_ps, 55, 75, 100)

axes[1,0].plot(x_ps, sedikit_ps, 'b-', linewidth=2, label='SEDIKIT')
axes[1,0].axvline(35, color='blue', linestyle='--', alpha=0.7)
axes[1,0].plot(35, 1.0, 'bo', markersize=8)
axes[1,0].set_title('4. Presentase Sinyal → SEDIKIT\nPS=35%, μ=1.0')
axes[1,0].set_xlabel('Presentase (%)')
axes[1,0].set_ylabel('μ')
axes[1,0].grid(True)
axes[1,0].legend()

axes[1,1].plot(x_ps, cukup_ps, 'g-', linewidth=2, label='CUKUP')
axes[1,1].axvline(36, color='green', linestyle='--', alpha=0.7)
axes[1,1].plot(36, 0.1, 'go', markersize=8)
axes[1,1].set_title('5. Presentase Sinyal → CUKUP\nPS=36%, μ=0.1')
axes[1,1].set_xlabel('Presentase (%)')
axes[1,1].set_ylabel('μ')
axes[1,1].grid(True)
axes[1,1].legend()

axes[1,2].plot(x_ps, banyak_ps, 'r-', linewidth=2, label='BANYAK')
axes[1,2].axvline(55, color='red', linestyle='--', alpha=0.7)
axes[1,2].plot(55, 1.0, 'ro', markersize=8)
axes[1,2].set_title('6. Presentase Sinyal → BANYAK\nPS=55%, μ=1.0')
axes[1,2].set_xlabel('Presentase (%)')
axes[1,2].set_ylabel('μ')
axes[1,2].grid(True)
axes[1,2].legend()

# 3. KONSISTENSI SINYAL (3 kurva)
x_ks = np.linspace(0, 1, 1000)
buruk_ks = triangular(x_ks, 0, 0.3, 0.5)
baik_ks = trapezoidal(x_ks, 0.3, 0.5, 0.7, 0.8)
sangat_baik_ks = triangular(x_ks, 0.7, 0.8, 1.0)

axes[2,0].plot(x_ks, buruk_ks, 'b-', linewidth=2, label='BURUK')
axes[2,0].axvline(0.0, color='blue', linestyle='--', alpha=0.7)
axes[2,0].plot(0.0, 0.0, 'bo', markersize=8)
axes[2,0].set_title('7. Konsistensi Sinyal → BURUK\nKS=0.0, μ=0.0')
axes[2,0].set_xlabel('Konsistensi')
axes[2,0].set_ylabel('μ')
axes[2,0].grid(True)
axes[2,0].legend()

axes[2,1].plot(x_ks, baik_ks, 'g-', linewidth=2, label='BAIK')
axes[2,1].axvline(0.8, color='green', linestyle='--', alpha=0.7)
axes[2,1].plot(0.8, 0.0, 'go', markersize=8)
axes[2,1].set_title('8. Konsistensi Sinyal → BAIK\nKS=0.8, μ=0.0')
axes[2,1].set_xlabel('Konsistensi')
axes[2,1].set_ylabel('μ')
axes[2,1].grid(True)
axes[2,1].legend()

axes[2,2].plot(x_ks, sangat_baik_ks, 'r-', linewidth=2, label='SANGAT BAIK')
axes[2,2].axvline(1.0, color='red', linestyle='--', alpha=0.7)
axes[2,2].plot(1.0, 0.0, 'ro', markersize=8)
axes[2,2].set_title('9. Konsistensi Sinyal → SANGAT BAIK\nKS=1.0, μ=0.0')
axes[2,2].set_xlabel('Konsistensi')
axes[2,2].set_ylabel('μ')
axes[2,2].grid(True)
axes[2,2].legend()

# 4. DATA RANDOM (3 kurva terakhir)
axes[3,0].plot(x_sr, low_sr, 'b-', linewidth=2, label='LOW')
axes[3,0].plot(x_sr, medium_sr, 'g-', linewidth=2, label='MEDIUM')
axes[3,0].axvline(4.2, color='purple', linestyle='--', alpha=0.7)
axes[3,0].plot(4.2, triangular(4.2, 0, 4, 5), 'bo', markersize=8, label='LOW: μ=0.8')
axes[3,0].plot(4.2, trapezoidal(4.2, 4, 5, 5.8, 6.2), 'go', markersize=8, label='MEDIUM: μ=0.2')
axes[3,0].set_title('10. Random → Skala Richter\nSR=4.2')
axes[3,0].set_xlabel('Skala Richter')
axes[3,0].set_ylabel('μ')
axes[3,0].grid(True)
axes[3,0].legend()

axes[3,1].plot(x_ps, sedikit_ps, 'b-', linewidth=2, label='SEDIKIT')
axes[3,1].plot(x_ps, cukup_ps, 'g-', linewidth=2, label='CUKUP')
axes[3,1].axvline(36, color='purple', linestyle='--', alpha=0.7)
axes[3,1].plot(36, triangular(36, 0, 35, 45), 'bo', markersize=8, label='SEDIKIT: μ=0.9')
axes[3,1].plot(36, trapezoidal(36, 35, 45, 55, 75), 'go', markersize=8, label='CUKUP: μ=0.1')
axes[3,1].set_title('11. Random → Presentase Sinyal\nPS=36%')
axes[3,1].set_xlabel('Presentase (%)')
axes[3,1].set_ylabel('μ')
axes[3,1].grid(True)
axes[3,1].legend()

axes[3,2].plot(x_ks, buruk_ks, 'b-', linewidth=2, label='BURUK')
axes[3,2].plot(x_ks, baik_ks, 'g-', linewidth=2, label='BAIK')
axes[3,2].plot(x_ks, sangat_baik_ks, 'r-', linewidth=2, label='SANGAT BAIK')
axes[3,2].axvline(0.6, color='purple', linestyle='--', alpha=0.7)
axes[3,2].plot(0.6, trapezoidal(0.6, 0.3, 0.5, 0.7, 0.8), 'go', markersize=8, label='BAIK: μ=1.0')
axes[3,2].set_title('12. Random → Konsistensi Sinyal\nKS=0.6')
axes[3,2].set_xlabel('Konsistensi')
axes[3,2].set_ylabel('μ')
axes[3,2].grid(True)
axes[3,2].legend()

plt.tight_layout()

# Perintah untuk menyimpan gambar
# plt.savefig(r'D:\Satriaalfa\Kuliah\Semester-5\Mk-Kecerdasan-buatan\kurva_resolusi_tinggi.png', dpi=300, bbox_inches='tight')

plt.show()

# # TAMPILKAN PERHITUNGAN
# print("=" * 50)
# print("HASIL PERHITUNGAN 12 DERAJAT KEANGGOTAAN")
# print("=" * 50)

# print("\n1. Skala Richter LOW (SR=4.0): μ = 1.0")
# print("2. Skala Richter MEDIUM (SR=4.1): μ = 0.1") 
# print("3. Skala Richter HIGH (SR=5.8): μ = 1.0")
# print("4. Presentase SEDIKIT (PS=35%): μ = 1.0")
# print("5. Presentase CUKUP (PS=36%): μ = 0.1")
# print("6. Presentase BANYAK (PS=55%): μ = 1.0")
# print("7. Konsistensi BURUK (KS=0.0): μ = 0.0")
# print("8. Konsistensi BAIK (KS=0.8): μ = 0.0")
# print("9. Konsistensi SANGAT BAIK (KS=1.0): μ = 0.0")
# print("10. Random SR=4.2 → LOW: μ=0.8, MEDIUM: μ=0.2")
# print("11. Random PS=36% → SEDIKIT: μ=0.9, CUKUP: μ=0.1")
# print("12. Random KS=0.6 → BAIK: μ=1.0")