# Rule 18: IF SEDANG AND BANYAK AND SANGAT_BAIK THEN TRUE
α18 = min(μ_MEDIUM, μ_BANYAK, μ_SANGAT_BAIK) = min(1.0, 0.0, 1.0) = 0.0

# Rule 24: IF TINGGI AND CUKUP AND SANGAT_BAIK THEN TRUE
α24 = min(μ_HIGH, μ_CUKUP, μ_SANGAT_BAIK) = min(0.0, 1.0, 1.0) = 0.0

# Rule 27: IF TINGGI AND BANYAK AND SANGAT_BAIK THEN TRUE  
α27 = min(μ_HIGH, μ_BANYAK, μ_SANGAT_BAIK) = min(0.0, 0.0, 1.0) = 0.0