# Rule 14: IF SEDANG AND CUKUP AND BAIK THEN TRUE
α14 = min(μ_MEDIUM, μ_CUKUP, μ_BAIK) = min(0.1, 0.1, 0.0) = 0.0

# Rule 15: IF SEDANG AND CUKUP AND SANGAT_BAIK THEN TRUE  
α15 = min(μ_MEDIUM, μ_CUKUP, μ_SANGAT_BAIK) = min(0.1, 0.1, 1.0) = 0.1

# Rule 17: IF SEDANG AND BANYAK AND BAIK THEN TRUE
α17 = min(μ_MEDIUM, μ_BANYAK, μ_BAIK) = min(0.1, 0.0, 0.0) = 0.0

# Rule 18: IF SEDANG AND BANYAK AND SANGAT_BAIK THEN TRUE
α18 = min(μ_MEDIUM, μ_BANYAK, μ_SANGAT_BAIK) = min(0.1, 0.0, 1.0) = 0.0